run-name: ci/cd python
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    # needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Package and Testers
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest ruff black flake8
      - name: Run Linters
        run: |
          black .
          flake8
          ruff check
      - name: Run Test
        run: pytest -s --verbose ./tests